Simplify option parsing

diff --git a/senv b/senv
--- a/senv
+++ b/senv
@@ -5,63 +5,41 @@ usage() {
   echo "usage: senv [-e | -d] <file>"
 }
 
-options=()
-arguments=()
-for arg in "$@"; do
-  if [ "${arg:0:1}" = "-" ]; then
-    if [ "${arg:1:1}" = "-" ]; then
-      options[${#options[*]}]="${arg:2}"
-    else
-      index=1
-      while option="${arg:$index:1}"; do
-        [ -n "$option" ] || break
-        options[${#options[*]}]="$option"
-        let index+=1
-      done
-    fi
-  else
-    arguments[${#arguments[*]}]="$arg"
-  fi
-done
-
 unset encrypt decrypt file
 
-for option in "${options[@]}"; do
-  case "$option" in
-  "e" | "encrypt" )
-    encrypt="1"
-    [ -t 0 ] && file=".env"
-    ;;
-  "d" | "decrypt" )
-    decrypt="1"
-    [ -t 0 ] && file=".senv"
-    ;;
-  * )
-    echo "senv: invalid option: --$option" >&2
-    usage >&2
-    exit 1
-    ;;
-  esac
-done
-
-if [ -n "$arguments" ]; then
-  file="$arguments"
+if [ "$1" = "-e" ] || [ "$1" = "--encrypt" ]; then
+  encrypt=1
+  [ -t 0 ] && file=".env"
+  shift
 fi
-if [ -t 0 ]; then
-  if [ -z "$file" ]; then
-    usage >&2
-    exit 1
-  elif [ ! -e "$file" ]; then
-    echo "senv: $file: No such file or directory" >&2
-    exit 1
-  elif [ ! -f "$file" ]; then
-    echo "senv: $file: Is a directory" >&2
-    exit 1
-  fi
-else
-  if [ -z "$file" ]; then
-    file="/dev/stdin"
-  fi
+
+if [ "$1" = "-d" ] || [ "$1" = "--decrypt" ]; then
+  decrypt=1
+  [ -t 0 ] && file=".senv"
+  shift
+fi
+
+if [ "${1:0:1}" = "-" ]; then
+  echo "senv: invalid option: $1" >&2
+  usage >&2
+  exit 1
+fi
+
+if [ -n "$1" ]; then
+  file="$1"
+fi
+
+if [ ! -t 0 ] && [ -z "$file" ]; then
+  file="/dev/stdin"
+elif [ -z "$file" ]; then
+  usage >&2
+  exit 1
+elif [ ! -e "$file" ]; then
+  echo "senv: $file: No such file or directory" >&2
+  exit 1
+elif [ ! -f "$file" ]; then
+  echo "senv: $file: Is a directory" >&2
+  exit 1
 fi
 
 if [ -z "$SENV_KEY" ]; then
